-- Access QueryDef: CnInvPmtUplTblNull
-- Нормализация staging CnInvPmtUplTbl: cacOrNull, «NullИлиПусто» для договора/СФ,
-- LEFT JOIN ags_cstAgPn / ags_cstAg.
-- Снято 2026-08-17 (режим SQL из Nav). Datasheet открывается.
-- Access принимает «b.a.ciputLink»: в сетке конструктора Поле = «a.ciputLink», таблица = b
-- (имя колонки подзапроса сохранило префикс внутреннего алиаса a; это не путь b.a.поле).

SELECT b.ciputBE, b.ciputAccount, b.ciputCntrPrtNum, b.ciputCntrPrtName, b.ciputCAC, b.cacOrNull, b.ciputAgentNum, b.ciputAgentName, b.ciputCnName, b.a.ciputLink, b.ciputCnInv, b.ciputEntryDate, b.ciputDocDate, b.ciputDueDate, b.ciputDbtBlns, b.ciputDbtBlnsOverd, b.ciputDbtBlnsOverdNot, b.ciputCdtBlns, b.ciputCdtBlnsOverd, b.ciputCdtBlnsOverdNot, b.ciputBlns, b.ciputCnInvDocCode, b.ciputAlligmentDate, b.ciputBaseDate, b.ciputCnInvDocSum, b.ciputStornoReason, b.ciputStornoDocCode, b.ciputSheetNum, b.ciputUnloadKey, p.cstapKey, p.cstapCsta, g.cstaAg
FROM ((SELECT a.ciputBE, a.ciputAccount, a.ciputCntrPrtNum, a.ciputCntrPrtName, a.ciputCAC, IIf(IsNull(a.ciputCAC) Or a.ciputCAC="",IIf(mid(a.ciputLink,4,1)="-" And len(a.ciputLink)>10,left(a.ciputLink,11),Null),IIf(Mid(a.ciputCAC,4,1)="-" And Len(a.ciputCAC)>10,Left(a.ciputCAC,11),Null)) AS cacOrNull, a.ciputAgentNum, a.ciputAgentName, IIf(IsNull(a.ciputCnName),"NullИлиПусто",IIf(a.ciputCnName="","NullИлиПусто",a.ciputCnName)) AS ciputCnName, a.ciputLink, IIf(IsNull(a.ciputCnInv),"NullИлиПусто",IIf(a.ciputCnInv="","NullИлиПусто",a.ciputCnInv)) AS ciputCnInv, a.ciputEntryDate, a.ciputDocDate, a.ciputDueDate, a.ciputDbtBlns, a.ciputDbtBlnsOverd, a.ciputDbtBlnsOverdNot, a.ciputCdtBlns, a.ciputCdtBlnsOverd, a.ciputCdtBlnsOverdNot, a.ciputBlns, a.ciputCnInvDocCode, a.ciputAlligmentDate, a.ciputBaseDate, a.ciputCnInvDocSum, a.ciputStornoReason, a.ciputStornoDocCode, a.ciputSheetNum, a.ciputUnloadKey FROM CnInvPmtUplTbl AS a)  AS b LEFT JOIN ags_cstAgPn AS p ON b.cacOrNull = p.cstapIpgPnN) LEFT JOIN ags_cstAg AS g ON p.cstapCsta = g.cstaKey;
